#!/usr/bin/env bash
# Generate the AUR-shaped PKGBUILD and .SRCINFO from the repository's own one.
#
# Two recipes for one package is how a package ships code nobody tested. So the
# PKGBUILD in the repository root stays the source of truth -- it is what
# `omdrop install-driver` runs, building from a clone -- and this derives the
# AUR variant from it mechanically:
#
#   - sources come from the release tarball at the v<pkgver> tag, not from
#     files sitting beside the recipe, because an AUR clone contains only
#     PKGBUILD and .SRCINFO
#   - ${startdir} becomes the unpacked tarball inside ${srcdir}
#
# Run it, commit aur/PKGBUILD and aur/.SRCINFO, and push aur/ to the AUR remote.
# Until the tarball exists at the tag its checksum cannot be computed, so the
# generated recipe carries SKIP and `--checksums` replaces it once the tag is
# pushed.
set -euo pipefail

here="$(cd "$(dirname "$0")" && pwd)"
root="$(cd "$here/.." && pwd)"
repo=$(basename "$root")          # the GitHub repository, which names the tarball
out="$here/PKGBUILD"

command -v makepkg >/dev/null || { echo "makepkg not found" >&2; exit 1; }

pkgver=$(awk -F= '/^pkgver=/ { print $2; exit }' "$root/PKGBUILD")
[[ -n $pkgver ]] || { echo "no pkgver in $root/PKGBUILD" >&2; exit 1; }

{
  echo "# GENERATED by aur/prepare.sh from the PKGBUILD in the repository root."
  echo "# Edit that one and re-run; edits here are overwritten."
  echo "#"
  python3 - "$root/PKGBUILD" "$repo" <<'PY'
import re, sys
src, repo = open(sys.argv[1]).read(), sys.argv[2]

# An AUR checkout has no patches/, userspace/ or packaging/ beside the recipe:
# it fetches the release tarball and reads them out of it.
src = re.sub(
    r"source=\((.*?)\)\nsha256sums=\((.*?)\)",
    'source=("linux-asahi::git+https://github.com/AsahiLinux/linux.git#tag=${_asahitag}"\n'
    f'        "$pkgname-$pkgver.tar.gz::$url/archive/v$pkgver.tar.gz")\n'
    "# The kernel tree is a git tag, which pins itself. The tarball's checksum is\n"
    "# filled in by `aur/prepare.sh --checksums` once the tag exists on GitHub.\n"
    "sha256sums=('SKIP'\n            'SKIP')",
    src, flags=re.S)

# Everything that read a file next to the recipe now reads it out of the
# unpacked tarball, which GitHub names <repo>-<version>.
src = src.replace("${startdir}", "${srcdir}/" + repo + "-${pkgver}")
src = src.replace("${srcdir}/dkms.conf.in",
                  "${srcdir}/" + repo + "-${pkgver}/dkms.conf.in")
print(src, end="")
PY
} > "$out"

# makepkg resolves `install=` beside the recipe, and an AUR checkout is only
# what is pushed to it -- so the hook file has to be there too. Copied rather
# than symlinked: git would carry the link, and the AUR clone would dangle.
pkgname=$(awk -F= '/^pkgname=/ { print $2; exit }' "$root/PKGBUILD")
install_file=$(awk -F= '/^install=/ { print $2; exit }' "$root/PKGBUILD")
install_file=${install_file//\"/}
install_file=${install_file//\$\{pkgname\}/$pkgname}
cp "$root/${install_file}" "$here/${install_file}"

if [[ ${1:-} == --checksums ]]; then
  command -v updpkgsums >/dev/null || { echo "updpkgsums needs pacman-contrib" >&2; exit 1; }
  ( cd "$here" && updpkgsums )
fi

( cd "$here" && makepkg --printsrcinfo > .SRCINFO )
echo "wrote $out and $here/.SRCINFO (pkgver $pkgver)"
grep -q "SKIP" "$here/.SRCINFO" && cat <<'MSG'

NOTE: the release tarball is still SKIP. Push the v<pkgver> tag to GitHub, then
      re-run with --checksums so the AUR recipe verifies what it downloads.
MSG
