#!/usr/bin/env bash
# Generate the AUR-shaped PKGBUILD and .SRCINFO from the repository's own one.
#
# Two recipes for one package is how a package ships code nobody tested. So the
# PKGBUILD in the repository root stays the source of truth -- it is what
# `omdrop install-driver` runs, building from a clone -- and this derives the
# AUR variant from it mechanically:
#
#   - sources come from the release tarball at the v<pkgver> tag, not from
#     files sitting beside the recipe, because an AUR clone contains only
#     PKGBUILD and .SRCINFO
#   - ${startdir} becomes the unpacked tarball inside ${srcdir}
#
# Run it, commit aur/PKGBUILD and aur/.SRCINFO, and push aur/ to the AUR remote.
# Until the tarball exists at the tag its checksum cannot be computed, so the
# generated recipe carries SKIP and `--checksums` replaces it once the tag is
# pushed.
set -euo pipefail

here="$(cd "$(dirname "$0")" && pwd)"
root="$(cd "$here/.." && pwd)"
repo=$(basename "$root")          # the GitHub repository, which names the tarball
out="$here/PKGBUILD"

command -v makepkg >/dev/null || { echo "makepkg not found" >&2; exit 1; }

pkgver=$(awk -F= '/^pkgver=/ { print $2; exit }' "$root/PKGBUILD")
[[ -n $pkgver ]] || { echo "no pkgver in $root/PKGBUILD" >&2; exit 1; }

{
  echo "# GENERATED by aur/prepare.sh from the PKGBUILD in the repository root."
  echo "# Edit that one and re-run; edits here are overwritten."
  echo "#"
  python3 - "$root/PKGBUILD" "$repo" <<'PY'
import re, sys
src, repo = open(sys.argv[1]).read(), sys.argv[2]

# An AUR checkout has no kernel/, patches/, userspace/ or packaging/ beside the
# recipe: it fetches the release tarball and reads them out of it. The vendored
# kernel sources travel inside that tarball, so the recipe downloads exactly one
# thing and never clones the kernel.
src = re.sub(
    r"source=\((.*?)\)\nsha256sums=\((.*?)\)",
    f'source=("$pkgname-$pkgver.tar.gz::$url/archive/v$pkgver.tar.gz")\n'
    "# Filled in by `aur/prepare.sh --checksums` once the tag exists on GitHub.\n"
    "sha256sums=('SKIP')",
    src, flags=re.S)

# Everything that read a file next to the recipe now reads it out of the
# unpacked tarball, which GitHub names <repo>-<version>.
src = src.replace("${startdir}", "${srcdir}/" + repo + "-${pkgver}")
src = src.replace("${srcdir}/dkms.conf.in",
                  "${srcdir}/" + repo + "-${pkgver}/dkms.conf.in")
print(src, end="")
PY
} > "$out"

# makepkg resolves `install=` beside the recipe, and an AUR checkout is only
# what is pushed to it -- so the hook file has to be there too. Copied rather
# than symlinked: git would carry the link, and the AUR clone would dangle.
pkgname=$(awk -F= '/^pkgname=/ { print $2; exit }' "$root/PKGBUILD")
install_file=$(awk -F= '/^install=/ { print $2; exit }' "$root/PKGBUILD")
install_file=${install_file//\"/}
install_file=${install_file//\$\{pkgname\}/$pkgname}
cp "$root/${install_file}" "$here/${install_file}"

if [[ ${1:-} == --checksums ]]; then
  # NOT updpkgsums: it retrieves every source, and one of them is a mirror
  # clone of the Asahi kernel -- gigabytes, minutes, and a bare repo left
  # behind in aur/. Only the tarball needs a checksum; the kernel source is a
  # git tag, which pins itself and is recorded as SKIP by design.
  url=$(awk -F= '/^url=/ { gsub(/"/, "", $2); print $2; exit }' "$root/PKGBUILD")
  tarball="${url}/archive/v${pkgver}.tar.gz"
  echo "hashing ${tarball}"
  sum=$(curl -fsSL "$tarball" | sha256sum | cut -d' ' -f1)
  [[ ${#sum} -eq 64 ]] || { echo "could not hash ${tarball}" >&2; exit 1; }
  # Second entry only: the first is the kernel tag.
  python3 - "$out" "$sum" <<'PY'
import re, sys
path, sum_ = sys.argv[1], sys.argv[2]
text = open(path).read()
text = re.sub(r"(sha256sums=\('SKIP'\n\s+')SKIP(')", r"\g<1>" + sum_ + r"\g<2>", text)
open(path, "w").write(text)
PY
fi

( cd "$here" && makepkg --printsrcinfo > .SRCINFO )
echo "wrote $out and $here/.SRCINFO (pkgver $pkgver)"
# The kernel source is a git tag and is SKIP by design, so the warning has to
# look at the tarball's own entry -- the second one -- not at any SKIP.
if [[ $(awk '/^sha256sums/ { getline; print }' "$out" | tr -d " '") == SKIP ]]; then
  cat <<'MSG'

NOTE: the release tarball is still SKIP. Push the v<pkgver> tag to GitHub, then
      re-run with --checksums so the AUR recipe verifies what it downloads.
MSG
fi
